### ISSUE TITLE
Migrate keystore to Metamask eth-keyring-controller

### ISSUE THREAD

**Issue by hashmesan** [harmony-one/onewallet#123]
## Motivation

To improve security of the storage, I'm proposing to use `eth-keyring-controller` which provides a unified enclave like way to sign transaction. The enclave/controller prevents any leakage of privateKey, stores multiple type of keyring in a standard way, and provide proper lock & unlock (Lock removes all the private key in memory store, which makes secure!)

## Tasks

- [x] evaluate the impact on the code
- [ ] need event passing between popup & background for add/remove wallet, and get wallets
- [ ] migrate function
- [ ] migrate UI
- [x] add wallet functionality
- [x] serialization of keyring-controller and meta data
- [ ] integrate wallets to the wallet menu UI
- [ ] integrate wallets to export UI
- [ ] integrate wallets to create UI
- [ ] integrate wallets to import UI
- [ ] signing transaction
- [ ] test with stake/unstake
- [ ] personal sign
- [ ] lock / unlock functionality
- [ ] regression testing on app
- [ ] test for injected script (API)
- [ ] alpha testing
- [ ] build & release

**Comment by hypnagonia** [comment]
@hashmesan nice proposal. we cease further wallet development and plan to migrate users to other wallets
